---

- name: Install Default Packages
  package: 
    name: "{{ item }}"
    state: latest
  with_items: 
    - vim
    - tmux
    - telnet
    - nc
    - traceroute
    - epel-release
    - sendmail

- name: Enesure services are started+enabled
  systemd:
    state: started
    name: "{{item}}"
    enabled: yes
  with_items:
    - sendmail

- name: Setup dot files
  copy: 
    src: "../files/{{item}}"
    dest: "/root/.{{item}}"
  with_items: 
    - tmux.conf
