---

- name: Install Default Packages
  package: 
    name: "{{ item }}"
    state: latest
  with_items: 
    - vim
    - tmux
    - telnet
    - nc
    - traceroute

- name: Setup dot files
  copy: 
    src: "../files/{{item}}"
    dest: "/root/.{{item}}"
  with_items: 
    - tmux.conf
